export const orgTypeOptions = [
  '',
  'Raýat',
  'Telekeçi',
  'Hojalyk jemgyýeti',
  'Hususy kärhana',
  'TS we T birleşmesi',
  'JGK',
  'Firma',
  'Döwlet kärhanasy',
  'Daýhan hojalygy',
  'Golçur kärhana',
  'Jemgyý.guramasynyň kärhanasy',
  'Alyjylar jemgyýet. birleşiginiň kärhanasy',
  'Bilelikdäki kärhana',
  'Açyk paýdarlar jemgyýeti',
  'Ýapyk paýdarlar jemgyýeti',
  'Hyzmatdaşlyk kärhanasy',
  'Jogapkärç. çäkl. şereket',
  'Jogapkärç. çäkl. jemgyýet',
  'Edara görnüşli taraplaryň birleşigi',
  'Daýhan birleşigi',
  'Assosiasiýa',
  'Konsern',
  'Korporasiýa',
  'Konsorsium',
  'Alyjylar jemgyýeti',
  'Alyjylar jemgyýet. birleşigi',
  'Edara',
  'Gazna',
  'Jemg-lik guramasy',
  'Jemg-lik hereketi',
  'Jemg-lik gaznasy',
  'Jemg-lik höwesjeňlik edarasy',
  'Syýasy partiýa',
  'Dini gurama',
  'Beýleki telekeçi däl tarap',
  'Wekillik',
  'Şahamça',
  'Kompaniýa',
  'Daşary ýurt kärhanasy',
  'Ýok',
  'Täze atlandyryş',
  'Aşgabat ş. häkimliginiň',
  'Lebap welaýatynyň',
];
